name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

